import Head from 'next/head'
import Avatar from '../components/Avatar'
import { ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon, MicrophoneIcon } from '@heroicons/react/outline'
import Image from 'next/image'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/google.png' />
      </Head>
      <header className='flex w-full p-5 justify-end text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          <ViewGridIcon
            className='cursor-pointer h-10 p-2 rounded-full 
          hover:bg-gray-100 w-10'
          />
          <Avatar url='https://i.postimg.cc/MZdQ43Kr/Whats-App-Image-2019-04-21-at-1-59-51-AM-01.jpg' />
        </div>
      </header>
      <form className = 'flex flex-col items-center mt-44 flex-grow'>
        <Image
          src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
          alt='google'
          height={100}
          width={300}
        />
        <div
          className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg
         max-w-md rounded-full border border-gray-200 px-5 py-3 items-center
         sm:max-w-xl lg:max-w-2xl'
        >
          <SearchIcon className='h-5 mr-3 text-gray-500' />
          <input
            type='text'
            className='flex-grow focus:outline-none'
          />
          <MicrophoneIcon className='h-5 text-gray-500' />
        </div>
        <div>
          <button className = 'btn'>Google Search</button>
          <button className = 'btn'>I'm Feeling Lucky</button>
        </div>
      </form>
    </div>
  )
}
